<template>
  <div class="app">
    <ThemeToggle />
    
    <header class="header">
      <h1>公益广告</h1>
      <p>投什么广告都是投，为什么不投一点更有意义的东西？</p>
    </header>
    
    <main class="main">
      <ClientOnly>
        <ContentDisplay />
        <template #fallback>
          <div class="loading">加载中...</div>
        </template>
      </ClientOnly>
    </main>
    
    <footer class="footer">
      <p>
        Generated by
        <a href="https://claude.ai/" style="color: #d97757">Claude</a> and
        <a href="https://gemini.google.com/app" style="color: #3983ff">Gemini</a>, managed by
        <a href="https://www.lynx3.me/" style="color: #ad7e0e">LynxCatTheThird</a>.
      </p>
    </footer>
  </div>
</template>

<style>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--bg-primary);
  overflow-x: hidden;
  transition: background-color 0.3s ease;
}

.header {
  background: var(--bg-secondary);
  padding: 24px 20px; /* 从 40px 减少到 24px */
  text-align: center;
  box-shadow: 0 2px 4px var(--shadow-sm);
  flex-shrink: 0;
  transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

.header h1 {
  font-size: 28px; /* 从 32px 减少到 28px */
  font-weight: bold;
  color: var(--text-primary);
  margin-bottom: 6px; /* 从 8px 减少到 6px */
  transition: color 0.3s ease;
}

.header p {
  font-size: 16px; /* 从 18px 减少到 16px */
  color: var(--text-secondary);
  transition: color 0.3s ease;
}

.main {
  flex: 1;
  padding: 40px 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 0;
}

.footer {
  background: var(--bg-secondary);
  padding: 32px 20px; /* 从 20px 增加到 32px */
  text-align: center;
  border-top: 1px solid var(--border-color);
  flex-shrink: 0;
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.footer p {
  font-size: 15px; /* 从 14px 增加到 15px */
  color: var(--text-tertiary);
  transition: color 0.3s ease;
  line-height: 1.6; /* 增加行高，让文字更舒适 */
  max-width: 600px;
  margin: 0 auto;
}

.loading {
  text-align: center;
  padding: 40px;
  color: var(--text-secondary);
}

@media (max-width: 640px) {
  .header {
    padding: 20px 15px; /* 从 30px 减少到 20px */
  }
  
  .header h1 {
    font-size: 22px; /* 从 24px 减少到 22px */
  }
  
  .header p {
    font-size: 14px; /* 从 16px 减少到 14px */
  }
  
  .main {
    padding: 20px 10px;
  }
  
  .footer {
    padding: 24px 15px; /* 移动端也相应增加 */
  }
  
  .footer p {
    font-size: 14px;
  }
}
</style>
