<template>
  <div class="app">
    <ThemeToggle />

    <header class="header">
      <h1>公益广告</h1>
      <p>投什么广告都是投，为什么不投一点更有意义的东西？</p>
    </header>

    <main class="main">
      <ClientOnly>
        <AdDisplay />
        <template #fallback>
          <div class="loading">加载中...</div>
        </template>
      </ClientOnly>
    </main>

    <footer class="footer">
      <p>
        Generated by
        <a href="https://claude.ai/" style="color: #d97757">Claude</a> and
        <a href="https://gemini.google.com/app" style="color: #3983ff">Gemini</a>, managed by
        <a href="https://www.lynx3.me/" style="color: #ad7e0e">LynxCatTheThird</a>.
      </p>
    </footer>
  </div>
</template>

<style>
.app {
  min-height: 100vh;
  display: flex;
  flex-grow: 1;
  flex-direction: column;
  background: var(--bg-primary);
  overflow-x: hidden;
  transition: background-color 0.3s ease;
}

.header {
  background: var(--bg-secondary);
  padding: 40px 20px;
  text-align: center;
  box-shadow: 0 2px 4px var(--shadow-sm);
  flex-shrink: 0;
  transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

.header h1 {
  font-size: 32px;
  font-weight: bold;
  color: var(--text-primary);
  margin-bottom: 8px;
  transition: color 0.3s ease;
}

.header p {
  font-size: 18px;
  color: var(--text-secondary);
  transition: color 0.3s ease;
}

.main {
  flex: 1;
  padding: 40px 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 0;
}

.footer {
  background: var(--bg-secondary);
  padding: 20px;
  text-align: center;
  border-top: 1px solid var(--border-color);
  flex-shrink: 0;
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.footer p {
  font-size: 14px;
  color: var(--text-tertiary);
  transition: color 0.3s ease;
}

.loading {
  text-align: center;
  padding: 40px;
  color: var(--text-secondary);
}

@media (max-width: 640px) {
  .header {
    padding: 30px 15px;
  }

  .header h1 {
    font-size: 24px;
  }

  .header p {
    font-size: 16px;
  }

  .main {
    padding: 20px 10px;
  }
}
</style>
